default["httpd"]["ServerAdmin"] = "root@localhost"
default["httpd"]["DocumentRoot"] = "/var/www/html"
default["httpd"]["ErrorLog"] = "logs/error_log"
default["httpd"]["LogLevel"] = "warn"
default["httpd"]["AddDefaultCharset"] = "UTF-8"
default["httpd"]["DirectoryIndex"] = "index.html index.html.var"
